ifneq ($(findstring $(TARGET),cooja native),)
$(info target $(TARGET))
#PROJECT_SOURCEFILES += sprintf.c snprintf.c strformat.c
SOURCE_EXCLUDE      += printf.c puts.c putchar.c
MODULES_SOURCES     := $(filter-out printf.c puts.c putchar.c, ${MODULES_SOURCES} )
endif